import type { Branded } from '@deepseek-ai/dsh-brand'

/** Canonical `provider/model` identity used inside the router. */
export type RouteKey = Branded<'RouteKey'>
/** Process-local identity correlating one physical attempt's durable route and failover facts. */
export type AutoRouteAttemptId = Branded<'AutoRouteAttemptId'>

/**
 * Brand a validated provider/model route identity.
 * @param key - canonical route identity.
 * @returns the same string, branded; no validation is performed.
 */
export function RouteKey(key: string): RouteKey {
  return key as RouteKey
}

/**
 * Brand one process-local attempt correlation identity.
 * @param id - unique identity generated by the owning attempt ledger.
 * @returns the same string, branded; no validation is performed.
 */
export function AutoRouteAttemptId(id: string): AutoRouteAttemptId {
  return id as AutoRouteAttemptId
}
